package com.cvconnect.enums;

import com.cvconnect.constant.Messages;
import lombok.Getter;
import nmquan.commonlib.exception.ErrorCode;
import org.springframework.http.HttpStatus;

@Getter
public enum CoreErrorCode implements ErrorCode {
    UPLOAD_FILE_QUANTITY_EXCEED_LIMIT(3001, Messages.UPLOAD_FILE_QUANTITY_EXCEED_LIMIT, HttpStatus.BAD_REQUEST),
    UPLOAD_FILE_ERROR(3002, Messages.UPLOAD_FILE_ERROR, HttpStatus.INTERNAL_SERVER_ERROR),
    FILE_FORMAT_NOT_SUPPORTED(3003, Messages.FILE_FORMAT_NOT_SUPPORTED, HttpStatus.BAD_REQUEST),
    ATTACH_FILE_NOT_FOUND(3004, Messages.ATTACH_FILE_NOT_FOUND, HttpStatus.NOT_FOUND),
    DOWNLOAD_FILE_FAILED(3005, Messages.DOWNLOAD_FILE_FAILED, HttpStatus.INTERNAL_SERVER_ERROR),
    INDUSTRY_NOT_FOUND(3006, Messages.INDUSTRY_NOT_FOUND, HttpStatus.NOT_FOUND),
    PROCESS_TYPE_CANNOT_DELETE_DEFAULT(3007, Messages.PROCESS_TYPE_CANNOT_DELETE_DEFAULT, HttpStatus.BAD_REQUEST),
    PROCESS_TYPE_CODE_DUPLICATED(3008, Messages.PROCESS_TYPE_CODE_DUPLICATED, HttpStatus.BAD_REQUEST),
    PROCESS_TYPE_NOT_FOUND(3009, Messages.PROCESS_TYPE_NOT_FOUND, HttpStatus.NOT_FOUND),
    INDUSTRY_EXCEED_LIMIT(3010, Messages.INDUSTRY_EXCEED_LIMIT, HttpStatus.BAD_REQUEST),
    LEVEL_NOT_FOUND(3011, Messages.LEVEL_NOT_FOUND, HttpStatus.NOT_FOUND),
    LEVEL_CODE_DUPLICATED(3012, Messages.LEVEL_CODE_DUPLICATED, HttpStatus.BAD_REQUEST),
    LEVEL_CANNOT_DELETE_DEFAULT(3013, Messages.LEVEL_CANNOT_DELETE_DEFAULT, HttpStatus.BAD_REQUEST),
    DEPARTMENT_NOT_FOUND(3014, Messages.DEPARTMENT_NOT_FOUND, HttpStatus.NOT_FOUND),
    DEPARTMENT_CODE_DUPLICATED(3015, Messages.DEPARTMENT_CODE_DUPLICATED, HttpStatus.BAD_REQUEST),
    DEPARTMENT_ORG_ID_REQUIRE(3016, Messages.DEPARTMENT_ORG_ID_REQUIRE, HttpStatus.BAD_REQUEST),
    POSITION_CODE_DUPLICATED(3017, Messages.POSITION_CODE_DUPLICATED, HttpStatus.BAD_REQUEST),
    FIRST_PROCESS_MUST_BE_APPLY(3018, Messages.FIRST_PROCESS_MUST_BE_APPLY, HttpStatus.BAD_REQUEST),
    LAST_PROCESS_MUST_BE_ONBOARD(3019, Messages.LAST_PROCESS_MUST_BE_ONBOARD, HttpStatus.NOT_FOUND),
    POSITION_NOT_FOUND(3020, Messages.POSITION_NOT_FOUND, HttpStatus.NOT_FOUND),
    INDUSTRY_CODE_ALREADY_EXISTS(3021, Messages.INDUSTRY_CODE_ALREADY_EXISTS, HttpStatus.BAD_REQUEST),
    CAREER_CODE_EXISTS(3023, Messages.CAREER_CODE_EXISTS, HttpStatus.BAD_REQUEST),
    DUE_DATE_MUST_BE_IN_FUTURE(3024, Messages.DUE_DATE_MUST_BE_IN_FUTURE, HttpStatus.BAD_REQUEST),
    ORG_POSITION_LEVEL_NOT_FOUND(3025, Messages.ORG_POSITION_LEVEL_NOT_FOUND, HttpStatus.NOT_FOUND),
    WORK_LOCATION_NOT_FOUND(3026, Messages.WORK_LOCATION_NOT_FOUND, HttpStatus.NOT_FOUND),
    SALARY_FROM_TO_INVALID(3027, Messages.SALARY_FROM_TO_INVALID, HttpStatus.BAD_REQUEST),
    JOB_AD_STATUS_INVALID(3029, Messages.JOB_AD_STATUS_INVALID, HttpStatus.BAD_REQUEST),
    EMAIL_TEMPLATE_ID_REQUIRED(3030, Messages.EMAIL_TEMPLATE_ID_REQUIRED, HttpStatus.BAD_REQUEST),
    EMAIL_TEMPLATE_NOT_FOUND(3031, Messages.EMAIL_TEMPLATE_NOT_FOUND, HttpStatus.NOT_FOUND),
    HR_CONTACT_NOT_FOUND(3032, Messages.HR_CONTACT_NOT_FOUND, HttpStatus.NOT_FOUND),
    FILE_TOO_LARGE(3033, Messages.FILE_TOO_LARGE, HttpStatus.BAD_REQUEST),
    CV_FILE_NOT_FOUND(3034, Messages.CV_FILE_NOT_FOUND, HttpStatus.BAD_REQUEST),
    FULL_NAME_REQUIRED(3035, Messages.FULL_NAME_REQUIRED, HttpStatus.BAD_REQUEST),
    EMAIL_REQUIRED(3036, Messages.EMAIL_REQUIRED, HttpStatus.BAD_REQUEST),
    PHONE_REQUIRED(3037, Messages.PHONE_REQUIRED, HttpStatus.BAD_REQUEST),
    CANDIDATE_NOT_FOUND(3038, Messages.CANDIDATE_NOT_FOUND, HttpStatus.NOT_FOUND),
    CANDIDATE_INFO_APPLY_NOT_FOUND(3039, Messages.CANDIDATE_INFO_APPLY_NOT_FOUND, HttpStatus.NOT_FOUND),
    JOB_AD_NOT_FOUND(3040, Messages.JOB_AD_NOT_FOUND, HttpStatus.NOT_FOUND),
    JOB_AD_EXPIRED(3041, Messages.JOB_AD_EXPIRED, HttpStatus.BAD_REQUEST),
    JOB_AD_STOP_RECRUITMENT(3042, Messages.JOB_AD_STOP_RECRUITMENT, HttpStatus.BAD_REQUEST),
    CANDIDATE_DUPLICATE_APPLY(3043, Messages.CANDIDATE_DUPLICATE_APPLY, HttpStatus.BAD_REQUEST),
    EMAIL_CONFIG_NOT_FOUND(3044, Messages.EMAIL_CONFIG_NOT_FOUND, HttpStatus.NOT_FOUND),
    ORG_NOT_FOUND(3045, Messages.ORG_NOT_FOUND, HttpStatus.NOT_FOUND),
    IMAGE_FILE_INVALID(3046, Messages.IMAGE_FILE_INVALID, HttpStatus.BAD_REQUEST),
    DOCUMENT_FILE_INVALID(3047, Messages.DOCUMENT_FILE_INVALID, HttpStatus.BAD_REQUEST),
    LEVEL_REQUIRED(3048, Messages.LEVEL_REQUIRED, HttpStatus.BAD_REQUEST),
    CAREER_NOT_FOUND(3049, Messages.CAREER_NOT_FOUND, HttpStatus.NOT_FOUND),
    INVALID_PROCESS_TYPE_CHANGE(3050, Messages.INVALID_PROCESS_TYPE_CHANGE, HttpStatus.BAD_REQUEST),
    EMAIL_SUBJECT_REQUIRED(3051, Messages.EMAIL_SUBJECT_REQUIRED, HttpStatus.BAD_REQUEST),
    EMAIL_TEMPLATE_REQUIRED(3052, Messages.EMAIL_TEMPLATE_REQUIRED, HttpStatus.BAD_REQUEST),
    CANDIDATE_ALREADY_ELIMINATED(3053, Messages.CANDIDATE_ALREADY_ELIMINATED, HttpStatus.BAD_REQUEST),
    ONBOARD_DATE_REQUIRED(3054, Messages.ONBOARD_DATE_REQUIRED, HttpStatus.BAD_REQUEST),
    ONBOARD_DATE_INVALID(3055, Messages.ONBOARD_DATE_INVALID, HttpStatus.BAD_REQUEST),
    CANDIDATE_ALREADY_ONBOARDED(3056, Messages.CANDIDATE_ALREADY_ONBOARDED, HttpStatus.BAD_REQUEST),
    CANDIDATE_NOT_IN_ONBOARD_PROCESS(3057, Messages.CANDIDATE_NOT_IN_ONBOARD_PROCESS, HttpStatus.BAD_REQUEST),
    MEETING_ADDRESS_NOT_NULL(3058, Messages.MEETING_ADDRESS_NOT_NULL, HttpStatus.BAD_REQUEST),
    MEETING_LINK_NOT_NULL(3059, Messages.MEETING_LINK_NOT_NULL, HttpStatus.BAD_REQUEST),
    DATE_BEFORE_TODAY(3060, Messages.DATE_BEFORE_TODAY, HttpStatus.BAD_REQUEST),
    DURATION_MINUTES_INVALID(3061, Messages.DURATION_MINUTES_INVALID, HttpStatus.BAD_REQUEST),
    CANDIDATE_INFO_EXISTS_NOT_IN_PROCESS(3062, Messages.CANDIDATE_INFO_EXISTS_NOT_IN_PROCESS, HttpStatus.BAD_REQUEST),
    CALENDAR_NOT_FOUND(3063, Messages.CALENDAR_NOT_FOUND, HttpStatus.NOT_FOUND),
    JOB_AD_STATUS_CANNOT_REVERT(3064, Messages.JOB_AD_STATUS_CANNOT_REVERT, HttpStatus.BAD_REQUEST),
    IS_AUTO_SEND_EMAIL_REQUIRED(3065, Messages.IS_AUTO_SEND_EMAIL_REQUIRED, HttpStatus.BAD_REQUEST),
    CANNOT_APPLY_OWN_ORG_JOB_AD(3066, Messages.CANNOT_APPLY_OWN_ORG_JOB_AD, HttpStatus.BAD_REQUEST),
    ORG_ADDRESS_AT_LEAST_ONE(3067, Messages.ORG_ADDRESS_AT_LEAST_ONE, HttpStatus.BAD_REQUEST),
    SCHEDULE_CONFLICT(3068, Messages.SCHEDULE_CONFLICT, HttpStatus.BAD_REQUEST),
    INVALID_INPUT(3069, Messages.INVALID_INPUT, HttpStatus.BAD_REQUEST)

    ;

    private final Integer code;
    private final String message;
    private final HttpStatus statusCode;

    CoreErrorCode(Integer code, String message, HttpStatus statusCode) {
        this.code = code;
        this.message = message;
        this.statusCode = statusCode;
    }

    @Override
    public HttpStatus getStatusCode() {
        return statusCode;
    }

    @Override
    public Integer getCode() {
        return code;
    }

    @Override
    public String getMessage() {
        return message;
    }
}
